version: '2'
services:
    web:
      build: ./www/python
      ports:
        - "5000:5000"
      volumes:
        - ./www/python:/code
      links:
        - redisserver
        - mongodb
    php:
      image: php:7-fpm
      volumes:
          - ./www:/www
    mongodb:
       image: mongo:latest
       environment:
         - MONGO_DATA_DIR=/data/db
         - MONGO_LOG_DIR=/dev/null
       volumes:
         - ./data/db:/data/db
       ports:
         - 27017:27017
       command: mongod --smallfiles --logpath=/dev/null
    redisserver:
       image: redis
       ports:
          - "6379:6379"
       volumes:
          - redisserver_data:/data
    mysql:
       image: mysql:latest
       ports:
         - "3306:3306"
       environment:
         - MYSQL_ROOT_PASSWORD="password"
volumes:
    mysql_data:
    mysql_log:
    redisserver_data: